name=EduWit
version=1.1.2
author=EduWit
maintainer=EduWit <developer@eduwit.com.mx>
sentence=Libreria oficial para aprender Arduino con las tarjetas EduBoard.
paragraph=API clara y progresiva para controlar la EduBoard UNO, sus actuadores, sensores y puertos de comunicacion desde Arduino IDE y mBlock.
category=Device Control
url=https://eduwit.com.mx
architectures=avr,esp32
includes=EduWit.h
