name=EduWit
version=1.0.0
author=EduWit
maintainer=EduWit <developer@eduwit.com.mx>
sentence=Libreria oficial del ecosistema de robotica educativa EduWit.
paragraph=Control integral para shields EduBoard (UNO, Profesional) y sensores modulares. Disenada para ninos, jovenes y proyectos de competencia STEAM.
category=Device Control
url=https://eduwit.com.mx
architectures=avr,esp32
includes=EduWit.h